name: client-e2e-workflow

on: pull_request

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '19'
          distribution: 'temurin'

      - name: Install dependencies
        run: cd client && npm install

      - name: Run Cypress e2e tests
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          browser: chrome
          wait-on: 'https://dev.quizz4all.paris-1.wilders.dev/quiz/play/**'
          wait-on-timeout: 60000
          record: false
          working-directory: ./client
          spec: 'cypress/e2e/quizplay.cy.ts'
