name: server-tests-workflow

on: pull_request

jobs:
  test-server:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'Java 21'
      - name: Run tests
        run: cd server && mvn test
