name: client-e2e-workflow

on: pull_request

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.1.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: quizzforall
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --host=localhost --password=root --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        volumes:
          - quizzdb:/var/lib/mysql

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '19'
          distribution: 'temurin'

      - name: Build Spring Boot Application
        run: |
          cd server
          chmod +x ./mvnw
          ./mvnw clean install

      - name: Install dependencies
        run: cd client && npm install

      - name: Run Cypress e2e tests
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          browser: chrome
          wait-on: 'http://localhost:4200'
          wait-on-timeout: 60000
          record: false
          working-directory: ./client
          spec: 'cypress/e2e/quizplay.cy.ts'
