name: client-e2e-workflow

on: pull_request

jobs:

  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '19'
          distribution: 'temurin'

      - name: Build Spring Boot Application
        run: ./mvnw clean install

      - name: Start Spring Boot Application
        run: java -jar target/server-0.0.1-SNAPSHOT.jar
        background: true

      - name: Wait for Spring Boot Application
        uses: eisenivan/wait-for-netlify-action@v1
        with:
          url: 'http://localhost:8080'
          timeout: 60

      - name: Install dependencies
        run: cd client && npm install

      - name: Run Cypress e2e tests
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
          browser: chrome
          wait-on: 'http://localhost:4200'
          wait-on-timeout: 60000
          record: false
          working-directory: ./client
          spec: 'cypress/e2e/quizplay.cy.ts' # Exécuter des tests spécifiques

