name: client-e2e-workflow

on: pull_request

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.1.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -p${MYSQL_ROOT_PASSWORD}"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '19'
          distribution: 'temurin'

      - name: Build Spring Boot Application
        run: |
          cd server
          chmod +x ./mvnw
          ./mvnw clean install



      - name: Install dependencies
        run: cd client && npm install

      - name: Run Cypress e2e tests
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          browser: chrome
          wait-on: 'http://localhost:4200'
          wait-on-timeout: 60000
          record: false
          working-directory: ./client
          spec: 'cypress/e2e/quizplay.cy.ts'
